import = [
    "~/.config/alacritty/themes/coolnight.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
dimensions = { columns = 100, lines = 34 }

opacity = 0.5
blur = true
decorations = "Buttonless"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16

normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
bold = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
italic = { family = "MesloLGS Nerd Font Mono", style = "Regular" }

offset = { x = 0, y = 0 }

glyph_offset = { x = 0, y = 0 }

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Block" }
unfocused_hollow = true

[mouse]
bindings = [
{ mouse = "Right", action = "PasteSelection" }
]
hide_when_typing = false

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[bell]
animation = "EaseOutExpo"
duration = 0

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "L", mods = "Control|Shift", chars = "l" },
{ key = "V", mods = "Command", action = "Paste" },
{ key = "C", mods = "Command", action = "Copy" },
{ key = "Paste", action = "Paste" },
{ key = "Copy", action = "Copy" },
{ key = "H", mods = "Command", action = "Hide" },
{ key = "Q", mods = "Command", action = "Quit" },
{ key = "W", mods = "Command", action = "Quit" },
{ key = "K", mods = "Command", action = "ClearHistory" }
]
